### ISSUE TITLE
Nearby stations do not load until a map is opened

### ISSUE THREAD

**Issue by neckcen** [timeforcoffee/timeforcoffee-android#16]
Firstly, thanks for bringing the best swiss public transport app over to android! Now on to the bug report.

Android version: 6.0.1
App version: 1.0.22

Problem:
When opening the app, the "stations" screen is stuck on the loading animation and absolutely nothing happens (I've let it run for 10 minutes). There is no indication in the taskbar that location/gps is being used either.

However if I open a map (through favourite or search) then go back to the station screen (without exiting the app) everything works as intended and I get a list of nearby stations. Whilst in map view, the location icon appears in the taskbar.

Additional information which may be of some use: my device is set to "device only" location mode, I have of course granted Time for Coffee the permission required to use location.

**Comment by nico6ka** [comment]
@neckcen Your issue was probably the same as #29. Could you confirm that the bug has been fixed in the last release? Thanks!

**Comment by neckcen** [comment]
Sadly, version 1.1.2 did not fix the problem. It's actually worse now as the app says "No favorites" until a station is opened through search, see below.

![screenshot_20171126-164452](https://user-images.githubusercontent.com/620960/33241689-58e65c16-d2c9-11e7-8b98-ef6b7cd2a467.png)

Note that this lets you add the same station twice as favorite (as favorites are somehow missing until going back to the app's opening screen after the search), see below.

![screenshot_20171126-164949](https://user-images.githubusercontent.com/620960/33241714-e055bbe2-d2c9-11e7-809f-fcee3c66684b.png)

**Comment by lucasardonini** [comment]
@neckcen Hi ! Thanks for the feedback. I will look at it asap :-)

**Comment by lucasardonini** [comment]
I think this issue is related to the usage of the "device only" location mode. I wasn't able to find a solution to this issue using this library but I just released an update that displays a warning message when this mode is enabled. I know it's a quickfix but we won't change the location library right now.

**Comment by neckcen** [comment]
A shame, but thank you for taking the time to investigate the issue!
